/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.skarev.spring.batch

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class SpringBatchApp

fun main(args: Array<String>) {
    SpringApplication.run(SpringBatchApp::class.java, *args)
}
